version: 2

builds:
  - id: airdash
    binary: airdash
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_NOTARY_ISSUER_ID" }}'
      ids:
        - airdash
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12_BASE64}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY_BASE64}}"

archives:
  - id: airdash-archive
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ljagiello
    name: airdash
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## AirDash {{ .Tag }} Release

    ### Installation (Apple Silicon only)

    Download the binary, extract it, and run:

    ```bash
    tar -xzf airdash_{{ .Version }}_darwin_arm64.tar.gz
    chmod +x airdash
    ./airdash
    ```

    The binary is signed and notarized for macOS.
